### ISSUE TITLE
Erro de validação de CNPJ

### ISSUE THREAD

**Issue by arielmoraes** [lira92/flunt.br#10]
Ao tentar validar o valor '0000000000abc' uma exceção `System.FormatException: 'Input string was not in a correct format.'` é lançada. Creio estar acontecendo por conta de uma tentativa de conversão para número.

**Comment by lira92** [comment]
@arielmoraes corrigido, instale a última versão do pacote para pegar a atualização: https://www.nuget.org/packages/Flunt.Br/1.1.3

Obrigado por reportar o problema!
