### ISSUE TITLE
Criar validação para Placa Veicular

### ISSUE THREAD

**Issue by lira92** [lira92/flunt.br#15]
Criar extensão que valida se um número de placa é válido, é interessante possuir opção de restringir somente formato mercosul, formato mais antigo (AAA-1111) ou ambos.

**Comment by luturol** [comment]
Posso pegar essa issue?

**Comment by lira92** [comment]
@luturol pode sim.

**Comment by luturol** [comment]
Olá,
Tenho uma dúvida sobre a issue.
Devo implementar também a extension dele? Assim consigo criar testes para validar o algoritmo.

**Comment by lira92** [comment]
@luturol sim.
