### ISSUE TITLE
Criar validação de CNH

### ISSUE THREAD

**Issue by lira92** [lira92/flunt.br#16]
Criar validação para Carteira Nacional de Habilitação.

Links de apoio:
https://gist.github.com/naldorp/4241ade12a427855e7c184cf0099060b
https://github.com/danielsouza/validarCNH

**Comment by leandrosdias** [comment]
Posso pegar essa issue?

**Comment by lira92** [comment]
@leandrosdias já tem alguns PR's abertos para essa issue.
