### ISSUE TITLE
Suporte ao GitFlow e Semantic Version

### ISSUE THREAD

**Issue by MarcosCostaDev** [lira92/flunt.br#3]
Uma sugestão é adicionar o gitflow no projeto, assim para trabalhar no cliente de quem faz um fork fica mais interessante e com isso se torna mais simples trabalhar com semantic version no projeto, uma vez que um hotfix (correção do branch master) gera uma versão 0.0.1 e uma feature (novo recurso adicionado a aplicação) gera a versão 0.1.0 no branch master.
Com isso fica mais fácil ver em qual versão tá, e sem falar nas tags automáticas de versão que o proprio gitflow faz.

Alguns links que podem dá uma orientação:
https://semver.org
https://github.com/petervanderdoes/gitflow-avh
https://danielkummer.github.io/git-flow-cheatsheet/index.pt_BR.html

Qualquer dúvida é só falar.

**Comment by lira92** [comment]
@marcoslcosta obrigado, irei dar uma olhada.

**Comment by lira92** [comment]
@marcoslcosta criei a branch develop no repositório para as features, pelo que entendi os contribuidores só precisam instalar o git flow na máquina para ter a facilidade dos comandos, acho que também seria interessantes criarmos um Contributing Guide

**Comment by MarcosCostaDev** [comment]
perfeitamente, assim novas features poderam ser colocadas no develop, onde os pull request irão para ele, e assim blinda o master, para depois de avaliar o develop, a gente faz o merge para master, criando o release.
