### ISSUE TITLE
Validação para CPF e CNPJ em apenas um método

### ISSUE THREAD

**Issue by danieljoris** [lira92/flunt.br#30]
A ideia dessa sugestão seria possibilitar a criação de um método que faça a validação tanto de um CPF quanto CNPJ, juntos. Ou seja, seria verificado se o valor é um CNPJ ou CPF(precisaria ser **necessariamente um dos dois tipos**).

Exemplo:

`AddNotifications(new Contract().IsCpfOrCnpj(document, "Document", "O documento não é um CPF ou CNPJ"));`

**Comment by toshiossada** [comment]
Também gostaria disso

**Comment by toshiossada** [comment]
abri PR https://github.com/lira92/flunt.br/pull/31 aguardo aprovação


ficara 

      .IsCnpjOrCPF(empresa.documento, "Documento", "Documento inválido")

**Comment by lira92** [comment]
Feature adicionada através do PR #31
