### ISSUE TITLE
Validação de CPF com problema quando há uso de valores literais

### ISSUE THREAD

**Issue by cboiam** [lira92/flunt.br#33]
Já submeti a solução, preciso de uma release pra atualizar no meu projeto (e remover o workaround).

**Comment by lira92** [comment]
@cboiam Opa, desculpa cara, acabei esquecendo de gerar a release, vou fazer assim que possível.

**Comment by cboiam** [comment]
@lira92 Muito obrigado 😄

**Comment by lira92** [comment]
@cboiam release criada.
