### ISSUE TITLE
Migração para v2

### ISSUE THREAD

**Issue by andrebaltieri** [lira92/flunt.br#35]
@lira92 estou reformulando o Flunt e vão ter várias Breaking Changes na v2, incluindo algumas que talvez afetem este pacote.

Seria legal já ir olhando a branch dev para alinharmos o lançamento!
https://github.com/andrebaltieri/Flunt/tree/dev

**Comment by lira92** [comment]
@andrebaltieri ok, vou dar uma olhada. Mas as alterações ainda estão em andamento, certo? Seria legal dar um ping quando tiver uma prerelease meio pronta.

**Comment by andrebaltieri** [comment]
v2 no ar!

**Comment by manacespereira** [comment]
E ai, ta dando erro kkkk

**Comment by lira92** [comment]
Opa @manacespereira não tenho conseguido dedicar tempo para ver sobre a versão 2, mas sei que o @andrebaltieri criou uma versão compatível, está aqui: https://www.nuget.org/packages/Flunt.Extensions.Br/

**Comment by yanjustino** [comment]
Fiz um pull request visando correção do problema

**Comment by lira92** [comment]
Versão publicada.
