### ISSUE TITLE
O nuget spec não está no projeto.

### ISSUE THREAD

**Issue by MarcosCostaDev** [lira92/flunt.br#4]
Seria interessante colocar o nuget spec no projeto, pois precisa colocar a dependencia da biblioteca flunt nele. 
Notei que no Readme, você mensiona a instalação como 

**Nuget**
```
Install-Package Flunt
```

**.NET CLI**
```
dotnet add package Flunt
```
e não

**Nuget**
```
Install-Package Flunt.Br
```

**.NET CLI**
```
dotnet add package Flunt.Br
```

seria interessante colocar no nuget spec a dependencia do Flunt

**Comment by lira92** [comment]
@marcoslcosta posso estar enganado, mas nas versões mais recentes do csproj como as dependências são definidas nele, não é necessário um aquivo nuget spec.

**Comment by MarcosCostaDev** [comment]
Ok então, é que ainda estou me aventurando no .netcore, e desconhecia essa feature.
