### ISSUE TITLE
Verificar a possibilidade de adicionar validações financeiras

### ISSUE THREAD

**Issue by MarcosCostaDev** [lira92/flunt.br#7]
A ideia, é trazer para o flunt.br algumas validações que normalmente alguns bancos tem em comum.
Como nosso número, digito nosso número, linha digitável.
Esse tipo de validação, normalmente o usuário deve passar algumas informações, como  agencia, conta caixa, entre outras informações.

Normalmente, as empresas criam rotinas para criação e validação desses números. Mas seria interessante já trazer a parte de validação dentro do flunt, uma vez que essas regras de criação quase nunca mudam, mesmo que cada banco tenha uma regra diferente. Acho interessante disponibilizar para alguns.

**Comment by lira92** [comment]
@marcoslcosta não sei se não fugiria muito do domínio que a lib se dispõe a resolver, validações de nosso número são respectivas a boletos e geralmente é necessário uma biblioteca que cuide de domínio inteiro dos boletos, não somente a validação.
