### ISSUE TITLE
Erro ao verificar CNPJ ou CPF quando o valor é nulo

### ISSUE THREAD

**Issue by arielmoraes** [lira92/flunt.br#8]
Ao verificar um CNPJ ou CPF o método de extensão deveria validar se o valor não está nulo.

**Comment by lira92** [comment]
@arielmoraes obrigado pelo feedback, vou alterar isso e lanço um novo release.

**Comment by lira92** [comment]
@arielmoraes corrigido e disponível no ultimo release do pacote https://www.nuget.org/packages/Flunt.Br/1.1.2
